module.exports = [
    {
        "ID": 48,
        "Type": "simple",
        "SKU": "woo-beanie",
        "Name": "Beanie",
        "Published": 1,
        "Is featured?": 0,
        "Visibility in catalog": "visible",
        "Short description": "This is a simple product.",
        "Description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": ".2",
        "Length (in)": 4,
        "Width (in)": 5,
        "Height (in)": ".5",
        "Allow customer reviews?": 1,
        "Purchase note": "",
        "Sale price": 18,
        "Regular price": 20,
        "Categories": "Clothing > Accessories",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/beanie-2.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 0,
        "Attribute 1 name": "Color",
        "Attribute 1 value(s)": "Red",
        "Attribute 1 visible": 1,
        "Attribute 1 global": 1,
        "Attribute 2 name": "",
        "Attribute 2 value(s)": "",
        "Attribute 2 visible": "",
        "Attribute 2 global": "",
        "Meta: _wpcom_is_markdown": 1,
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 58,
        "Type": "simple",
        "SKU": "woo-belt",
        "Name": "Belt",
        "Published": 1,
        "Is featured?": 0,
        "Visibility in catalog": "visible",
        "Short description": "This is a simple product.",
        "Description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": 1.2,
        "Length (in)": 12,
        "Width (in)": 2,
        "Height (in)": 1.5,
        "Allow customer reviews?": 1,
        "Purchase note": "",
        "Sale price": 55,
        "Regular price": 65,
        "Categories": "Clothing > Accessories",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/belt-2.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 0,
        "Attribute 1 name": "",
        "Attribute 1 value(s)": "",
        "Attribute 1 visible": "",
        "Attribute 1 global": "",
        "Attribute 2 name": "",
        "Attribute 2 value(s)": "",
        "Attribute 2 visible": "",
        "Attribute 2 global": "",
        "Meta: _wpcom_is_markdown": 1,
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 60,
        "Type": "simple",
        "SKU": "woo-cap",
        "Name": "Cap",
        "Published": 1,
        "Is featured?": 1,
        "Visibility in catalog": "visible",
        "Short description": "This is a simple product.",
        "Description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": 0.6,
        "Length (in)": 8,
        "Width (in)": 6.5,
        "Height (in)": 4,
        "Allow customer reviews?": 1,
        "Purchase note": "",
        "Sale price": 16,
        "Regular price": 18,
        "Categories": "Clothing > Accessories",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/cap-2.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 0,
        "Attribute 1 name": "Color",
        "Attribute 1 value(s)": "Yellow",
        "Attribute 1 visible": 1,
        "Attribute 1 global": 1,
        "Attribute 2 name": "",
        "Attribute 2 value(s)": "",
        "Attribute 2 visible": "",
        "Attribute 2 global": "",
        "Meta: _wpcom_is_markdown": 1,
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 62,
        "Type": "simple",
        "SKU": "woo-sunglasses",
        "Name": "Sunglasses",
        "Published": 1,
        "Is featured?": 1,
        "Visibility in catalog": "visible",
        "Short description": "This is a simple product.",
        "Description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": ".2",
        "Length (in)": 4,
        "Width (in)": 1.4,
        "Height (in)": 1,
        "Allow customer reviews?": 1,
        "Purchase note": "",
        "Sale price": "",
        "Regular price": 90,
        "Categories": "Clothing > Accessories",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/sunglasses-2.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 0,
        "Attribute 1 name": "",
        "Attribute 1 value(s)": "",
        "Attribute 1 visible": "",
        "Attribute 1 global": "",
        "Attribute 2 name": "",
        "Attribute 2 value(s)": "",
        "Attribute 2 visible": "",
        "Attribute 2 global": "",
        "Meta: _wpcom_is_markdown": 1,
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 64,
        "Type": "simple",
        "SKU": "woo-hoodie-with-pocket",
        "Name": "Hoodie with Pocket",
        "Published": 1,
        "Is featured?": 1,
        "Visibility in catalog": "hidden",
        "Short description": "This is a simple product.",
        "Description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": 3,
        "Length (in)": 10,
        "Width (in)": 8,
        "Height (in)": 2,
        "Allow customer reviews?": 1,
        "Purchase note": "",
        "Sale price": 35,
        "Regular price": 45,
        "Categories": "Clothing > Hoodies",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/hoodie-with-pocket-2.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 0,
        "Attribute 1 name": "Color",
        "Attribute 1 value(s)": "Gray",
        "Attribute 1 visible": 1,
        "Attribute 1 global": 1,
        "Attribute 2 name": "",
        "Attribute 2 value(s)": "",
        "Attribute 2 visible": "",
        "Attribute 2 global": "",
        "Meta: _wpcom_is_markdown": 1,
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 66,
        "Type": "simple",
        "SKU": "woo-hoodie-with-zipper",
        "Name": "Hoodie with Zipper",
        "Published": 1,
        "Is featured?": 1,
        "Visibility in catalog": "visible",
        "Short description": "This is a simple product.",
        "Description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": 2,
        "Length (in)": 8,
        "Width (in)": 6,
        "Height (in)": 2,
        "Allow customer reviews?": 1,
        "Purchase note": "",
        "Sale price": "",
        "Regular price": 45,
        "Categories": "Clothing > Hoodies",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/hoodie-with-zipper-2.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 0,
        "Attribute 1 name": "",
        "Attribute 1 value(s)": "",
        "Attribute 1 visible": "",
        "Attribute 1 global": "",
        "Attribute 2 name": "",
        "Attribute 2 value(s)": "",
        "Attribute 2 visible": "",
        "Attribute 2 global": "",
        "Meta: _wpcom_is_markdown": 1,
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 68,
        "Type": "simple",
        "SKU": "woo-long-sleeve-tee",
        "Name": "Long Sleeve Tee",
        "Published": 1,
        "Is featured?": 0,
        "Visibility in catalog": "visible",
        "Short description": "This is a simple product.",
        "Description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": 1,
        "Length (in)": 7,
        "Width (in)": 5,
        "Height (in)": 1,
        "Allow customer reviews?": 1,
        "Purchase note": "",
        "Sale price": "",
        "Regular price": 25,
        "Categories": "Clothing > Tshirts",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/long-sleeve-tee-2.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 0,
        "Attribute 1 name": "Color",
        "Attribute 1 value(s)": "Green",
        "Attribute 1 visible": 1,
        "Attribute 1 global": 1,
        "Attribute 2 name": "",
        "Attribute 2 value(s)": "",
        "Attribute 2 visible": "",
        "Attribute 2 global": "",
        "Meta: _wpcom_is_markdown": 1,
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 70,
        "Type": "simple",
        "SKU": "woo-polo",
        "Name": "Polo",
        "Published": 1,
        "Is featured?": 0,
        "Visibility in catalog": "visible",
        "Short description": "This is a simple product.",
        "Description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": ".8",
        "Length (in)": 6,
        "Width (in)": 5,
        "Height (in)": 1,
        "Allow customer reviews?": 1,
        "Purchase note": "",
        "Sale price": "",
        "Regular price": 20,
        "Categories": "Clothing > Tshirts",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/polo-2.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 0,
        "Attribute 1 name": "Color",
        "Attribute 1 value(s)": "Blue",
        "Attribute 1 visible": 1,
        "Attribute 1 global": 1,
        "Attribute 2 name": "",
        "Attribute 2 value(s)": "",
        "Attribute 2 visible": "",
        "Attribute 2 global": "",
        "Meta: _wpcom_is_markdown": 1,
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 73,
        "Type": "simple, downloadable, virtual",
        "SKU": "woo-album",
        "Name": "Album",
        "Published": 1,
        "Is featured?": 0,
        "Visibility in catalog": "visible",
        "Short description": "This is a simple, virtual product.",
        "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": "",
        "Length (in)": "",
        "Width (in)": "",
        "Height (in)": "",
        "Allow customer reviews?": 1,
        "Purchase note": "",
        "Sale price": "",
        "Regular price": 15,
        "Categories": "Music",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/album-1.jpg",
        "Download limit": 1,
        "Download expiry days": 1,
        "Parent": "",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 0,
        "Attribute 1 name": "",
        "Attribute 1 value(s)": "",
        "Attribute 1 visible": "",
        "Attribute 1 global": "",
        "Attribute 2 name": "",
        "Attribute 2 value(s)": "",
        "Attribute 2 visible": "",
        "Attribute 2 global": "",
        "Meta: _wpcom_is_markdown": 1,
        "Download 1 name": "Single 1",
        "Download 1 URL": "https://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2017/08/single.jpg",
        "Download 2 name": "Single 2",
        "Download 2 URL": "https://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2017/08/album.jpg"
    },
    {
        "ID": 75,
        "Type": "simple, downloadable, virtual",
        "SKU": "woo-single",
        "Name": "Single",
        "Published": 1,
        "Is featured?": 0,
        "Visibility in catalog": "visible",
        "Short description": "This is a simple, virtual product.",
        "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": "",
        "Length (in)": "",
        "Width (in)": "",
        "Height (in)": "",
        "Allow customer reviews?": 1,
        "Purchase note": "",
        "Sale price": 2,
        "Regular price": 3,
        "Categories": "Music",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/single-1.jpg",
        "Download limit": 1,
        "Download expiry days": 1,
        "Parent": "",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 0,
        "Attribute 1 name": "",
        "Attribute 1 value(s)": "",
        "Attribute 1 visible": "",
        "Attribute 1 global": "",
        "Attribute 2 name": "",
        "Attribute 2 value(s)": "",
        "Attribute 2 visible": "",
        "Attribute 2 global": "",
        "Meta: _wpcom_is_markdown": 1,
        "Download 1 name": "Single",
        "Download 1 URL": "https://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2017/08/single.jpg",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 76,
        "Type": "variation",
        "SKU": "woo-vneck-tee-red",
        "Name": "V-Neck T-Shirt - Red",
        "Published": 1,
        "Is featured?": 0,
        "Visibility in catalog": "visible",
        "Short description": "",
        "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": "",
        "Length (in)": "",
        "Width (in)": "",
        "Height (in)": "",
        "Allow customer reviews?": 0,
        "Purchase note": "",
        "Sale price": "",
        "Regular price": 20,
        "Categories": "",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/vneck-tee-2.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "woo-vneck-tee",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 0,
        "Attribute 1 name": "Color",
        "Attribute 1 value(s)": "Red",
        "Attribute 1 visible": "",
        "Attribute 1 global": 1,
        "Attribute 2 name": "Size",
        "Attribute 2 value(s)": "",
        "Attribute 2 visible": "",
        "Attribute 2 global": 1,
        "Meta: _wpcom_is_markdown": "",
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 77,
        "Type": "variation",
        "SKU": "woo-vneck-tee-green",
        "Name": "V-Neck T-Shirt - Green",
        "Published": 1,
        "Is featured?": 0,
        "Visibility in catalog": "visible",
        "Short description": "",
        "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": "",
        "Length (in)": "",
        "Width (in)": "",
        "Height (in)": "",
        "Allow customer reviews?": 0,
        "Purchase note": "",
        "Sale price": "",
        "Regular price": 20,
        "Categories": "",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/vnech-tee-green-1.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "woo-vneck-tee",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 0,
        "Attribute 1 name": "Color",
        "Attribute 1 value(s)": "Green",
        "Attribute 1 visible": "",
        "Attribute 1 global": 1,
        "Attribute 2 name": "Size",
        "Attribute 2 value(s)": "",
        "Attribute 2 visible": "",
        "Attribute 2 global": 1,
        "Meta: _wpcom_is_markdown": "",
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 78,
        "Type": "variation",
        "SKU": "woo-vneck-tee-blue",
        "Name": "V-Neck T-Shirt - Blue",
        "Published": 1,
        "Is featured?": 0,
        "Visibility in catalog": "visible",
        "Short description": "",
        "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": "",
        "Length (in)": "",
        "Width (in)": "",
        "Height (in)": "",
        "Allow customer reviews?": 0,
        "Purchase note": "",
        "Sale price": "",
        "Regular price": 15,
        "Categories": "",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/vnech-tee-blue-1.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "woo-vneck-tee",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 0,
        "Attribute 1 name": "Color",
        "Attribute 1 value(s)": "Blue",
        "Attribute 1 visible": "",
        "Attribute 1 global": 1,
        "Attribute 2 name": "Size",
        "Attribute 2 value(s)": "",
        "Attribute 2 visible": "",
        "Attribute 2 global": 1,
        "Meta: _wpcom_is_markdown": "",
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 79,
        "Type": "variation",
        "SKU": "woo-hoodie-red",
        "Name": "Hoodie - Red, No",
        "Published": 1,
        "Is featured?": 0,
        "Visibility in catalog": "visible",
        "Short description": "",
        "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": "",
        "Length (in)": "",
        "Width (in)": "",
        "Height (in)": "",
        "Allow customer reviews?": 0,
        "Purchase note": "",
        "Sale price": 42,
        "Regular price": 45,
        "Categories": "",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/hoodie-2.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "woo-hoodie",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 1,
        "Attribute 1 name": "Color",
        "Attribute 1 value(s)": "Red",
        "Attribute 1 visible": "",
        "Attribute 1 global": 1,
        "Attribute 2 name": "Logo",
        "Attribute 2 value(s)": "No",
        "Attribute 2 visible": "",
        "Attribute 2 global": 0,
        "Meta: _wpcom_is_markdown": "",
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 80,
        "Type": "variation",
        "SKU": "woo-hoodie-green",
        "Name": "Hoodie - Green, No",
        "Published": 1,
        "Is featured?": 0,
        "Visibility in catalog": "visible",
        "Short description": "",
        "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": "",
        "Length (in)": "",
        "Width (in)": "",
        "Height (in)": "",
        "Allow customer reviews?": 0,
        "Purchase note": "",
        "Sale price": "",
        "Regular price": 45,
        "Categories": "",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/hoodie-green-1.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "woo-hoodie",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 2,
        "Attribute 1 name": "Color",
        "Attribute 1 value(s)": "Green",
        "Attribute 1 visible": "",
        "Attribute 1 global": 1,
        "Attribute 2 name": "Logo",
        "Attribute 2 value(s)": "No",
        "Attribute 2 visible": "",
        "Attribute 2 global": 0,
        "Meta: _wpcom_is_markdown": "",
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 81,
        "Type": "variation",
        "SKU": "woo-hoodie-blue",
        "Name": "Hoodie - Blue, No",
        "Published": 1,
        "Is featured?": 0,
        "Visibility in catalog": "visible",
        "Short description": "",
        "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": "",
        "Length (in)": "",
        "Width (in)": "",
        "Height (in)": "",
        "Allow customer reviews?": 0,
        "Purchase note": "",
        "Sale price": "",
        "Regular price": 45,
        "Categories": "",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/hoodie-blue-1.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "woo-hoodie",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 3,
        "Attribute 1 name": "Color",
        "Attribute 1 value(s)": "Blue",
        "Attribute 1 visible": "",
        "Attribute 1 global": 1,
        "Attribute 2 name": "Logo",
        "Attribute 2 value(s)": "No",
        "Attribute 2 visible": "",
        "Attribute 2 global": 0,
        "Meta: _wpcom_is_markdown": "",
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 83,
        "Type": "simple",
        "SKU": "Woo-tshirt-logo",
        "Name": "T-Shirt with Logo",
        "Published": 1,
        "Is featured?": 0,
        "Visibility in catalog": "visible",
        "Short description": "This is a simple product.",
        "Description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": ".5",
        "Length (in)": 10,
        "Width (in)": 12,
        "Height (in)": ".5",
        "Allow customer reviews?": 1,
        "Purchase note": "",
        "Sale price": "",
        "Regular price": 18,
        "Categories": "Clothing > Tshirts",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/t-shirt-with-logo-1.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 0,
        "Attribute 1 name": "Color",
        "Attribute 1 value(s)": "Gray",
        "Attribute 1 visible": 1,
        "Attribute 1 global": 1,
        "Attribute 2 name": "",
        "Attribute 2 value(s)": "",
        "Attribute 2 visible": "",
        "Attribute 2 global": "",
        "Meta: _wpcom_is_markdown": 1,
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 85,
        "Type": "simple",
        "SKU": "Woo-beanie-logo",
        "Name": "Beanie with Logo",
        "Published": 1,
        "Is featured?": 0,
        "Visibility in catalog": "visible",
        "Short description": "This is a simple product.",
        "Description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": ".2",
        "Length (in)": 6,
        "Width (in)": 4,
        "Height (in)": 1,
        "Allow customer reviews?": 1,
        "Purchase note": "",
        "Sale price": 18,
        "Regular price": 20,
        "Categories": "Clothing > Accessories",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/beanie-with-logo-1.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 0,
        "Attribute 1 name": "Color",
        "Attribute 1 value(s)": "Red",
        "Attribute 1 visible": 1,
        "Attribute 1 global": 1,
        "Attribute 2 name": "",
        "Attribute 2 value(s)": "",
        "Attribute 2 visible": "",
        "Attribute 2 global": "",
        "Meta: _wpcom_is_markdown": 1,
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 87,
        "Type": "grouped",
        "SKU": "logo-collection",
        "Name": "Logo Collection",
        "Published": 1,
        "Is featured?": 0,
        "Visibility in catalog": "visible",
        "Short description": "This is a grouped product.",
        "Description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": "",
        "Length (in)": "",
        "Width (in)": "",
        "Height (in)": "",
        "Allow customer reviews?": 1,
        "Purchase note": "",
        "Sale price": "",
        "Regular price": "",
        "Categories": "Clothing",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/logo-1.jpg, https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/beanie-with-logo-1.jpg, https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/t-shirt-with-logo-1.jpg, https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/hoodie-with-logo-2.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "",
        "Grouped products": "woo-hoodie-with-logo, woo-tshirt, woo-beanie",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 0,
        "Attribute 1 name": "",
        "Attribute 1 value(s)": "",
        "Attribute 1 visible": "",
        "Attribute 1 global": "",
        "Attribute 2 name": "",
        "Attribute 2 value(s)": "",
        "Attribute 2 visible": "",
        "Attribute 2 global": "",
        "Meta: _wpcom_is_markdown": 1,
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 89,
        "Type": "external",
        "SKU": "wp-pennant",
        "Name": "WordPress Pennant",
        "Published": 1,
        "Is featured?": 0,
        "Visibility in catalog": "visible",
        "Short description": "This is an external product.",
        "Description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": "",
        "Length (in)": "",
        "Width (in)": "",
        "Height (in)": "",
        "Allow customer reviews?": 1,
        "Purchase note": "",
        "Sale price": "",
        "Regular price": 11.05,
        "Categories": "Decor",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/pennant-1.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "https://mercantile.wordpress.org/product/wordpress-pennant/",
        "Button text": "Buy on the WordPress swag store!",
        "Position": 0,
        "Attribute 1 name": "",
        "Attribute 1 value(s)": "",
        "Attribute 1 visible": "",
        "Attribute 1 global": "",
        "Attribute 2 name": "",
        "Attribute 2 value(s)": "",
        "Attribute 2 visible": "",
        "Attribute 2 global": "",
        "Meta: _wpcom_is_markdown": 1,
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    },
    {
        "ID": 90,
        "Type": "variation",
        "SKU": "woo-hoodie-blue-logo",
        "Name": "Hoodie - Blue, Yes",
        "Published": 1,
        "Is featured?": 0,
        "Visibility in catalog": "visible",
        "Short description": "",
        "Description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sagittis orci ac odio dictum tincidunt. Donec ut metus leo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed luctus, dui eu sagittis sodales, nulla nibh sagittis augue, vel porttitor diam enim non metus. Vestibulum aliquam augue neque. Phasellus tincidunt odio eget ullamcorper efficitur. Cras placerat ut turpis pellentesque vulputate. Nam sed consequat tortor. Curabitur finibus sapien dolor. Ut eleifend tellus nec erat pulvinar dignissim. Nam non arcu purus. Vivamus et massa massa.",
        "Date sale price starts": "",
        "Date sale price ends": "",
        "Tax status": "taxable",
        "Tax class": "",
        "In stock?": 1,
        "Stock": "",
        "Backorders allowed?": 0,
        "Sold individually?": 0,
        "Weight (lbs)": "",
        "Length (in)": "",
        "Width (in)": "",
        "Height (in)": "",
        "Allow customer reviews?": 0,
        "Purchase note": "",
        "Sale price": "",
        "Regular price": 45,
        "Categories": "",
        "Tags": "",
        "Shipping class": "",
        "Images": "https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/hoodie-with-logo-2.jpg",
        "Download limit": "",
        "Download expiry days": "",
        "Parent": "woo-hoodie",
        "Grouped products": "",
        "Upsells": "",
        "Cross-sells": "",
        "External URL": "",
        "Button text": "",
        "Position": 0,
        "Attribute 1 name": "Color",
        "Attribute 1 value(s)": "Blue",
        "Attribute 1 visible": "",
        "Attribute 1 global": 1,
        "Attribute 2 name": "Logo",
        "Attribute 2 value(s)": "Yes",
        "Attribute 2 visible": "",
        "Attribute 2 global": 0,
        "Meta: _wpcom_is_markdown": "",
        "Download 1 name": "",
        "Download 1 URL": "",
        "Download 2 name": "",
        "Download 2 URL": ""
    }
];
